# Generated by Django 2.1.1 on 2018-09-08 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sess',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
